name: Hanson Musical Instruments
favicon: null
layout_spectrum: 0.9593
typography_spectrum: 0.84779
title: 'Musical instrument makers and repairers.  Marsden, West Yorkshire.  Established 1989'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121212'
    - '#7b7462'
    - '#403d36'
    - '#9d9680'
    - '#f5f6f3'
  brandStrength: 0.25
  lightness: 0.15473741758614779
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
