name: Hanson Musical Instruments
favicon: null
layout_spectrum: 0.4984232580754906
typography_spectrum: 0.4807940705213696
title: 'Musical instrument makers and repairers.  Marsden, West Yorkshire.  Established 1989'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0b10'
    - '#65696c'
    - '#e2ca6c'
    - '#8f9088'
    - '#feffec'
  brandStrength: 0.7661141990683973
  lightness: 0.15473741758614779
  saturation: 0.8866848878096789
  rhythmicContrast: 0.7562738622073084
purpose: []
